### ISSUE TITLE
Too many pandas

### ISSUE THREAD

**Issue by sahf27** [Cozary/Red-Panda#1]
I don't know if this is a bug or not, but whenever I am in a jungle the longer I am there the more pandas  spawn until it is over 20 or more around me. I am playing with other mods so I don't know if any of them are messing with spawn rates. I am playing in fabric 1.21 and also have living things installed.

**Comment by Cozary** [comment]
I think I did something wrong in fabric with the spawns

**Comment by Cozary** [comment]
Versions with the fix should be appearing shortly.
